image: "rust:latest"

stages:
  - build
  - test

build-job:
  stage: build
  artifacts:
    paths:
      - target/release/indivisible
  script:
    - cargo build --release

test-job:
  stage: test
  script:
    - ./test.sh

include:
  - template: Security/License-Scanning.gitlab-ci.yml
